<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>DshBar</AssemblyName>
    <RootNamespace>DshBar</RootNamespace>
    <Version>0.3.0</Version>
    <ApplicationIcon>Assets\whale.ico</ApplicationIcon>
    <!-- 单文件发布默认启用压缩，避免遗忘导致体积翻倍 -->
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\whale.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.*" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.*" />
  </ItemGroup>

</Project>
